### ISSUE TITLE
about social_viualize in social-lstm

### ISSUE THREAD

**Issue by seekku** [SZamboni/Social_lstm_pedestrian_prediction#5]
hi, I have some problems as follows:

Traceback (most recent call last):
  File "social_lstm/social_visualize.py", line 103, in <module>
    main()
  File "social_lstm/social_visualize.py", line 97, in main
    plot_trajectories(results[i][0], results[i][1], results[i][2],name)
  File "social_lstm/social_visualize.py", line 81, in plot_trajectories
    plt.savefig('plot/'+name+'.png')
………………
ValueError: Invalid RGBA argument: array([[0.54852619],
       [0.61438593],
       [0.82290634]])
Process finished with exit code 1

How can i solve this problem?

**Comment by SZamboni** [comment]
Hi,

Thank you for your feedback. Unfortunately it has been a long time since I worked on this project and at the time I was only a beginner of deep learning and Python. Thus, I am afraid I cannot help you. 
I think you would maybe find more helpful the repository of SocialGAN, which is better maintained and has more usable data, you can find it at https://github.com/agrimgupta92/sgan.
